--Explorar la tabla “menu_items” para conocer los productos del menú.

SELECT * FROM MENU_ITEMS;


--Encontrar el número de artículos en el menú.
SELECT COUNT(ITEM_NAME)
FROM  MENU_ITEMS;


--¿Cuál es el artículo menos caro y el más caro en el menú?
SELECT ITEM_NAME, PRICE
FROM MENU_ITEMS
ORDER BY PRICE;

--¿Cuántos platos americanos hay en el menú?
SELECT ITEM_NAME, CATEGORY
FROM MENU_ITEMS
WHERE CATEGORY ILIKE ('AMERICAN');


--¿Cuál es el precio promedio de los platos?
SELECT ROUND(AVG(PRICE),2)
FROM MENU_ITEMS;


--Explorar la tabla “order_details”
--para conocer los datos que han sido recolectados.
SELECT * FROM ORDER_DETAILS;


--¿Cuántos pedidos únicos se realizaron en total?
SELECT DISTINCT COUNT(ORDER_ID)
FROM ORDER_DETAILS;


--¿Cuáles son los 5 pedidos que tuvieron el mayor número de artículos?
SELECT ORDER_ID, COUNT(ITEM_ID)
FROM ORDER_DETAILS
GROUP BY ORDER_ID
ORDER BY COUNT(ITEM_ID) DESC
LIMIT 5;


--¿Cuándo se realizó el primer pedido y el último pedido?
SELECT MIN (ORDER_DATE) AS PRIMER_PEDIDO, MAX (ORDER_DATE) AS ULTIMO_PEDIDO
FROM ORDER_DETAILS; 


--¿Cuántos pedidos se hicieron entre el '2023-01-01' y el '2023-01-05'?
SELECT COUNT(ORDER_DATE)
FROM ORDER_DETAILS
WHERE ORDER_DATE BETWEEN '2023-01-01' AND '2023-01-05';


--Usar ambas tablas para conocer la reacción de los clientes respecto al menú.
SELECT *
FROM ORDER_DETAILS AS O
LEFT JOIN MENU_ITEMS AS M
ON O.ITEM_ID=M.MENU_ITEM_ID;

--1.-
SELECT COUNT(O.ORDER_ID), M.ITEM_NAME
FROM ORDER_DETAILS AS O
LEFT JOIN MENU_ITEMS AS M
ON O.ITEM_ID=M.MENU_ITEM_ID
GROUP BY M.ITEM_NAME
ORDER BY COUNT(O.ORDER_ID) DESC;


--2.-
SELECT COUNT(O.ORDER_ID), M.ITEM_NAME
FROM ORDER_DETAILS AS O
LEFT JOIN MENU_ITEMS AS M
ON O.ITEM_ID=M.MENU_ITEM_ID
GROUP BY M.ITEM_NAME
ORDER BY COUNT(O.ORDER_ID) ASC
LIMIT 1;


--3.-
SELECT COUNT(O.ORDER_ID), M.CATEGORY
FROM ORDER_DETAILS AS O
LEFT JOIN MENU_ITEMS AS M
ON O.ITEM_ID=M.MENU_ITEM_ID
GROUP BY M.CATEGORY
ORDER BY COUNT(O.ORDER_ID) ASC;


--4.-
SELECT COUNT(O.ORDER_ID), M.CATEGORY
FROM ORDER_DETAILS AS O
LEFT JOIN MENU_ITEMS AS M
ON O.ITEM_ID=M.MENU_ITEM_ID
GROUP BY M.CATEGORY
ORDER BY COUNT(O.ORDER_ID) DESC
LIMIT 1;


--5.-
SELECT COUNT(O.ORDER_ID), M.ITEM_NAME
FROM ORDER_DETAILS AS O
LEFT JOIN MENU_ITEMS AS M
ON O.ITEM_ID=M.MENU_ITEM_ID
GROUP BY M.ITEM_NAME
ORDER BY COUNT(O.ORDER_ID) DESC
LIMIT 3;